type LaptopCompares = {
	id: number;
	colors: string[];
	image: string;
	title: string;
	sub: string;
	path: string;
	data: {
		display: string;
		screen: string;
		chip: string;
		chipImage: string;
		cpu: string;
		cpu_size: string;
		gpu: string;
		gpu_size: string;
		memoryImage: string;
		memorySize: string;
		storage: string;
		storageDesc: string;
		bateraiImage: string;
		bateraiDesc: string;
		faceTimeImage: string;
		faceTimeDesc: string;
		speakerImage: string;
		speakerDesc: string;
		weight: string;
		touchId: string;
		ppi?: string;
	}[];
};
type DesktopCompares = {
	id: number;
	colors: string[];
	image: string;
	title: string;
	color: string;
	path: string;
	data: {
		display: string;
		screen: string;
		ppi: string;
		chip: string;
		chipImage: string;
		cpu: string;
		cpu_size: string;
		gpu: string;
		gpu_size: string;
		memoryImage: string;
		memorySize: string;
		storage: string;
		storageDesc: string;
		bateraiImage: string;
		bateraiDesc: string;
		faceTimeImage: string;
		faceTimeDesc: string;
		facetimeSub: string;
		speakerImage: string;
		speakerDesc: string;
		weight: string;
	}[];
};
